version: '3.8'
services:
  db:
    image: postgres
    container_name: peop-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL='postgresql://peop:p3oPr00t@peop-db:5432/peop?schema=public'
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - '5432:5432'
    volumes:
      - peop-pgdata:/var/lib/postgresql/data
    networks:
      - peop-network
networks:
  peop-network:
volumes:
  peop-pgdata:
